### ISSUE TITLE
pytest-cov==1.8.1 + pytest-xdist does not show coverage report 

### ISSUE THREAD

**Issue by diefans** [schlamar/pytest-cov#54]
the latest `pytest-cov==1.8.1` together with xdist does not show the coverage report anymore.

`pytest-cov==1.6` works

```
# pip freeze | grep pytest
pytest==2.7.1
pytest-cache==1.0
pytest-cov==1.8.1
pytest-pep8==1.0.6
pytest-random==0.2
pytest-xdist==1.12
```

**Comment by ionelmc** [comment]
@diefans Is the report empty? Do you get any warnings?

**Comment by diefans** [comment]
It is just not there. No warnings. As I would have called it without `--cov package`

**Comment by ionelmc** [comment]
Does it still reproduce with the master branch (`pip install https://github.com/schlamar/pytest-cov/archive/master.zip`)?

**Comment by diefans** [comment]
Master does not fix it :(

**Comment by ionelmc** [comment]
Show the configurations you use (setup.cfg, pytest.ini, .coveragerc etc).

Also, show a tree of your project (run `tree`).

**Comment by diefans** [comment]
my pytest section looks like:
```
[pytest]
addopts=-rf --strict --pep8 --cov-report term-missing --cov-config coveragerc --color yes --random --random-group
pep8maxlinelength = 120
pep8ignore=
    */migrations/* ALL
```
`.coveragerc`
```
# .coveragerc to control coverage.py
[run]
branch = True

[report]
# Regexes for lines to exclude from consideration
exclude_lines =
    # Have to re-enable the standard pragma
    pragma: no cover

    # Don't complain about missing debug-only code:
    def __repr__
    if self\.debug

    # Don't complain if tests don't hit defensive assertion code:
    raise AssertionError
    raise NotImplementedError

    # Don't complain if non-runnable code isn't run:
    if 0:
    if __name__ == .__main__.:

ignore_errors = True
precision = 2
omit=
```


pytest and plugins
```
# pip freeze | grep pytest
pytest==2.7.2
pytest-cache==1.0
pytest-cov==2.0.0
pytest-ipdb==0.1.dev2
pytest-pep8==1.0.6
pytest-random==0.2
pytest-xdist==1.12
```

**Comment by ionelmc** [comment]
Project layout? (run `tree`)

**Comment by diefans** [comment]
Its a bit big but you can also checkout http://github.com/diefans/python-arangodb
```
.
├── build
│   ├── bdist.linux-x86_64
│   └── lib.linux-x86_64-2.7
│       └── arangodb
│           ├── api.py
│           ├── cursor.py
│           ├── db.py
│           ├── exc.py
│           ├── graph.py
│           ├── __init__.py
│           ├── meta.py
│           ├── query.py
│           └── util.py
├── dist
│   └── arangodb-0.0.12-py2.py3-none-any.whl
├── docs
│   ├── build
│   │   ├── doctrees
│   │   │   ├── alabaster
│   │   │   │   └── README.doctree
│   │   │   ├── environment.pickle
│   │   │   └── index.doctree
│   │   └── html
│   │       ├── alabaster
│   │       │   └── README.html
│   │       ├── genindex.html
│   │       ├── index.html
│   │       ├── _modules
│   │       │   ├── arangodb
│   │       │   │   ├── api.html
│   │       │   │   ├── cursor.html
│   │       │   │   ├── db.html
│   │       │   │   ├── meta.html
│   │       │   │   └── query.html
│   │       │   └── index.html
│   │       ├── objects.inv
│   │       ├── py-modindex.html
│   │       ├── search.html
│   │       ├── searchindex.js
│   │       ├── _sources
│   │       │   ├── alabaster
│   │       │   │   └── README.txt
│   │       │   └── index.txt
│   │       └── _static
│   │           ├── ajax-loader.gif
│   │           ├── alabaster.css
│   │           ├── basic.css
│   │           ├── comment-bright.png
│   │           ├── comment-close.png
│   │           ├── comment.png
│   │           ├── doctools.js
│   │           ├── down.png
│   │           ├── down-pressed.png
│   │           ├── file.png
│   │           ├── jquery-1.11.1.js
│   │           ├── jquery.js
│   │           ├── minus.png
│   │           ├── plus.png
│   │           ├── pygments.css
│   │           ├── searchtools.js
│   │           ├── underscore-1.3.1.js
│   │           ├── underscore.js
│   │           ├── up.png
│   │           ├── up-pressed.png
│   │           └── websupport.js
│   ├── Makefile
│   └── source
│       ├── alabaster
│       │   ├── alabaster
│       │   │   ├── about.html
│       │   │   ├── donate.html
│       │   │   ├── __init__.py
│       │   │   ├── layout.html
│       │   │   ├── navigation.html
│       │   │   ├── static
│       │   │   │   └── alabaster.css_t
│       │   │   ├── support.py
│       │   │   ├── theme.conf
│       │   │   └── _version.py
│       │   ├── dev-requirements.txt
│       │   ├── LICENSE
│       │   ├── MANIFEST.in
│       │   ├── README.rst
│       │   ├── setup.py
│       │   └── tasks.py
│       ├── conf.py
│       ├── index.rst
│       ├── _static
│       └── _templates
├── LICENSE
├── pytest.ini
├── README.rst
├── requirements-test.pip
├── setup.cfg
├── setup.py
├── setup.pyc
├── src
│   ├── arangodb
│   │   ├── api.py
│   │   ├── api.pyc
│   │   ├── cursor.py
│   │   ├── cursor.pyc
│   │   ├── db.py
│   │   ├── db.pyc
│   │   ├── exc.py
│   │   ├── exc.py.bak
│   │   ├── exc.pyc
│   │   ├── graph.py
│   │   ├── graph.py.bak
│   │   ├── graph.pyc
│   │   ├── __init__.py
│   │   ├── __init__.pyc
│   │   ├── meta.py
│   │   ├── meta.py.bak
│   │   ├── meta.pyc
│   │   ├── __pycache__
│   │   │   ├── api.cpython-34.pyc
│   │   │   ├── cursor.cpython-34.pyc
│   │   │   ├── db.cpython-34.pyc
│   │   │   ├── exc.cpython-34.pyc
│   │   │   ├── graph.cpython-27-PYTEST.pyc
│   │   │   ├── graph.cpython-34.pyc
│   │   │   ├── __init__.cpython-34.pyc
│   │   │   ├── meta.cpython-34.pyc
│   │   │   ├── query.cpython-34.pyc
│   │   │   └── util.cpython-34.pyc
│   │   ├── query.py
│   │   ├── query.py.bak
│   │   ├── query.pyc
│   │   ├── util.py
│   │   └── util.pyc
│   └── arangodb.egg-info
│       ├── dependency_links.txt
│       ├── namespace_packages.txt
│       ├── PKG-INFO
│       ├── requires.txt
│       ├── SOURCES.txt
│       └── top_level.txt
└── tests
    ├── conftest.py
    ├── conftest.pyc
    ├── db
    │   ├── __pycache__
    │   │   ├── test_edge.cpython-27-PYTEST.pyc
    │   │   ├── test_edge.cpython-34.pyc
    │   │   └── test_edge.cpython-34-PYTEST.pyc
    │   ├── test_edge.py
    │   └── test_edge.pyc
    ├── __pycache__
    │   ├── conftest.cpython-34.pyc
    │   ├── test_cursor.cpython-27-PYTEST.pyc
    │   ├── test_cursor.cpython-34.pyc
    │   ├── test_cursor.cpython-34-PYTEST.pyc
    │   ├── test_document.cpython-27-PYTEST.pyc
    │   ├── test_document.cpython-34.pyc
    │   ├── test_document.cpython-34-PYTEST.pyc
    │   ├── test_edge.cpython-27-PYTEST.pyc
    │   ├── test_graph.cpython-27-PYTEST.pyc
    │   ├── test_graph.cpython-34.pyc
    │   ├── test_graph.cpython-34-PYTEST.pyc
    │   ├── test_query.cpython-27-PYTEST.pyc
    │   ├── test_query.cpython-34.pyc
    │   └── test_query.cpython-34-PYTEST.pyc
    ├── test_cursor.py
    ├── test_cursor.pyc
    ├── test_document.py
    ├── test_document.pyc
    ├── test_edge.pyc
    ├── test_graph.py
    ├── test_graph.pyc
    ├── test_query.py
    └── test_query.pyc

30 directories, 142 files
```

**Comment by ionelmc** [comment]
Ok I've just tried this locally. Looks like the pep8 plugin is causing the problem.

**Comment by diefans** [comment]
mhhh.....
I just created a fresh virtual env only with `pytest`, `pytest-cov` and `pytest-xdist` and its still the same for me.

**Comment by ionelmc** [comment]
Ook, and also removed the `--pep8` option?

**Comment by diefans** [comment]
yes, totally removed pytest section.

I made an observation:
running `py.test tests --cov arangodb` leaves a `.coverage` file, while `py.test tests --cov arangodb -f` leaves two files `.coverage.hugin.loc.6736.284156` and `.coverage.hugin.loc.6736.451023`

**Comment by ionelmc** [comment]
`--cov arangodb` is invalid afaik, it should be a path. Try `--cov=src`. However, because you use a `src` project layout you have to install your code in develop mode (eg: `setup.py develop` or `pip install -e .`).

**Comment by diefans** [comment]
IMHO the syntax is totally valid as I may select also subpackages e.g. `--cov arangodb.util`, what makes totally sense when working with big code bases

Lets not forget, that when installing `pytest-cov==1.6` everything works as expected, so I would consider the actual behaviour a regression...

**Comment by ionelmc** [comment]
Yes, but I'm not exactly familiar with what changed between 1.6 and 1.8 ...

I've tried your project. It works fine with 1.8.1, eg
```
.ve/bin/py.test tests --cov=src                                                                                                                                           
============================================================================================================ test session starts ============================================================================================================
platform linux2 -- Python 2.7.3 -- py-1.4.30 -- pytest-2.7.2
Tests are shuffled using seed number 367840457165.
rootdir: /home/ionel/osp/python-arangodb, inifile: pytest.ini
plugins: cache, cov, pylama, greendots, pep8, xdist, random
collected 33 items

tests/test_graph.py E
tests/test_query.py ...
tests/test_graph.py s
tests/test_document.py .
tests/db/test_edge.py .
tests/test_query.py .
tests/db/test_edge.py s
tests/conftest.py s
tests/test_query.py .....
tests/test_graph.py .
tests/test_query.py ..s.
tests/db/test_edge.py .
tests/test_query.py ...
tests/test_document.py s
tests/test_query.py ......
tests/test_cursor.py s
tests/db/test_edge.py .

================================================================================================================== ERRORS ===================================================================================================================
_______________________________________________________________________________________________________ ERROR at setup of test_graph ________________________________________________________________________________________________________

    @pytest.fixture(scope="session")
    def docker_client():
>       from docker import Client
E       ImportError: No module named docker

tests/conftest.py:10: ImportError
---------------------------------------------------------------------------------------------- coverage: platform linux2, python 2.7.3-final-0 ----------------------------------------------------------------------------------------------
Name                    Stmts   Miss  Cover   Missing
-----------------------------------------------------
src/arangodb/__init__       1      0   100%
src/arangodb/api          175    110    37%   27-57, 70-95, 100, 104, 108, 112, 116, 119, 123, 128-134, 142-145, 150-155, 164-165, 170, 178, 183-189, 194, 207-209, 214-223, 231-236, 245-255, 260, 265, 270-275, 286-292, 298-303, 306, 309, 312, 318-324, 337-351, 356, 359, 370-380, 385-394, 401
src/arangodb/cursor        23     15    35%   13-15, 20-32, 39-40, 43-44
src/arangodb/db            86     28    67%   17, 26, 59, 86, 90, 94, 98, 104-108, 118-123, 151, 158, 162, 188-197, 200-208
src/arangodb/exc           50     11    78%   34, 44-47, 60-68
src/arangodb/graph         12      0   100%
src/arangodb/meta         264    100    62%   34, 42, 48-52, 56, 97, 111-125, 131-140, 144, 167, 174, 181, 188, 197, 229-231, 234-237, 240-243, 247, 263, 271, 275-277, 294, 306, 313-320, 327-340, 348, 352-368, 380-382, 404, 410, 416, 419, 422, 425-427, 435, 445, 449, 453, 457, 461, 469-470, 476, 482-485, 491, 500-508, 518, 531, 570, 575-588, 593
src/arangodb/query        491     24    95%   39, 125, 135, 180, 231, 240, 264-267, 274, 298, 317, 644, 675, 678, 716, 719, 727, 730, 733, 768-770, 798-800
src/arangodb/util           5      0   100%
-----------------------------------------------------
TOTAL                    1107    288    74%
=============================================================================================== 26 passed, 6 skipped, 1 error in 0.16 seconds ===============================================================================================
```

You must be doing something wrong on your side. I recommend you to use https://testrun.org/tox/ for managing the virtualenv, it can save you from lots of pain :)

**Comment by diefans** [comment]
ok here is the simplest way to reproduce:
```
TEST_DIR=/tmp/pytest-cov-issue

# make module available to python
export PYTHONPATH=${TEST_DIR}

mkdir ${TEST_DIR}

cat > ${TEST_DIR}/module.py << EOF
def foo(x):
    if x:
        return 1
    return 2
EOF

cat > ${TEST_DIR}/test_module.py << EOF
def test_module_1():
    import module
    assert module.foo(True) == 1
EOF

# install pytest
virtualenv ${TEST_DIR}/.venv

${TEST_DIR}/.venv/bin/pip install pytest pytest-cov pytest-xdist

# this should show coverage
(cd ${TEST_DIR}; .venv/bin/py.test test_module.py --cov module)

# this is missing coverage
(cd ${TEST_DIR}; .venv/bin/py.test test_module.py --cov module -f)

```

**Comment by ionelmc** [comment]
Ok, much more clear now. So it's an issue with `--looponfail` (xdist) right?

**Comment by diefans** [comment]
ergh.... ok I was not clear enough. I am sorry.

`-f` or `--looponfail` causes the missing coverage

**Comment by schlamar** [comment]
`looponfail` is not supported (right now). 

Has the behavior of `looponfail` changed lately? When I had a look at it the last time (around #11) I thought that the behavior of `looponfail` was that it spins forever (without a full run at the end), so coverage in combination with `looponfail` didn't make sense.

**Comment by schlamar** [comment]
However, this is strange:

> pytest-cov==1.6 works

**Comment by ionelmc** [comment]
1.6 doesn't support xdist at all does it?

**Comment by schlamar** [comment]
> 1.6 doesn't support xdist at all does it?

It does... 

I just did a git bisect. This issue was introduced by commit 5d9ba4bb147075e74dda7fbffc9ccaa90183dfe5.

**Comment by ionelmc** [comment]
Interesting. What was the intent in that commit?

**Comment by schlamar** [comment]
> What was the intent in that commit?

That coverage is active before importing a `conftest.py`. So this was a very important improvement, however apparently this added a regression (which I was not aware of when dealing with #11).

Between fixing #11 and this commit running with `looponfail` crashes with an exception:

      File "/tmp/pytest-cov-issue/.venv/lib/python2.7/site-packages/_pytest/core.py", line 123, in __init__
        self.result = func()
      File "/tmp/pytest-cov-issue/.venv/lib/python2.7/site-packages/_pytest/core.py", line 394, in execute
        res = method(*args)
      File "/tmp/pytest-cov-issue/.venv/lib/python2.7/site-packages/pytest_cov.py", line 118, in pytest_sessionfinish
        self.cov_controller.finish()
    AttributeError: 'NoneType' object has no attribute 'finish'

**Comment by ionelmc** [comment]
PS. I think it would make sense to release 2.0 before tackling this - fix is not obvious, at least for me :grimacing:

**Comment by schlamar** [comment]
The cause is not starting coverage in `pytest_configure`: https://github.com/schlamar/pytest-cov/commit/5d9ba4bb147075e74dda7fbffc9ccaa90183dfe5#diff-b11c22be59918991abb98626c1adff2dR46

So I have an idea how to solve this (start the plugin in pytest_sessionstart if the plugin was not started yet).

**Comment by diefans** [comment]
> so coverage in combination with looponfail didn't make sense.

looponfail does a complete test run after you are done by implementing/fixing tdd-tests

**Comment by schlamar** [comment]
> looponfail does a complete test run after you are done by implementing/fixing tdd-tests

Not really (with your test case from https://github.com/schlamar/pytest-cov/issues/54#issuecomment-121228289 and pytest-xdist 1.12) but I'm still going to fix this...

**Comment by schlamar** [comment]
Fixed in master
